// SuperAdmin/frontend/src/pages/Login/Login.tsx
import React, { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useAuth } from '../../context/AuthContext'
import { Zap, AlertCircle } from 'lucide-react'

export default function Login() {
  const { login } = useAuth()
  const navigate = useNavigate()

  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(false)

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setError('')
    setLoading(true)
    try {
      await login(email, password)
      navigate('/dashboard')
    } catch {
      setError('Invalid credentials. Please try again.')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="min-h-screen flex" style={{ background: '#0d1117' }}>
      {/* Left panel */}
      <div
        className="hidden lg:flex flex-col justify-between w-1/2 p-12 border-r border-gray-800"
        style={{ background: '#0d1117' }}
      >
        <div className="flex items-center gap-3">
          <div className="w-9 h-9 rounded-xl bg-orange-500 flex items-center justify-center flex-shrink-0">
            <Zap size={18} className="text-white" fill="white" />
          </div>
          <div>
            <p className="text-sm font-bold text-white leading-tight">FastFood</p>
            <p className="text-xs text-gray-500 leading-tight">Super Admin</p>
          </div>
        </div>

        <div>
          <div className="mb-8 inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-orange-500/10 border border-orange-500/20">
            <Zap size={32} className="text-orange-500" fill="currentColor" />
          </div>
          <h2 className="text-4xl font-bold text-white leading-tight mb-4">
            Manage your<br />
            <span className="text-orange-500">FastFood</span> empire
          </h2>
          <p className="text-gray-500 text-lg leading-relaxed">
            One dashboard to rule all stores, drivers,<br />
            subscriptions, and orders across the platform.
          </p>
        </div>

        <div className="flex gap-6 text-xs text-gray-700">
          <span>Platform v1.0</span>
          <span>© 2026 FastFood SaaS</span>
        </div>
      </div>

      {/* Right panel */}
      <div
        className="flex flex-1 items-center justify-center px-6 py-12"
        style={{ background: '#161b22' }}
      >
        <div className="w-full max-w-sm">
          {/* Mobile logo */}
          <div className="flex items-center gap-3 mb-8 lg:hidden">
            <div className="w-9 h-9 rounded-xl bg-orange-500 flex items-center justify-center">
              <Zap size={18} className="text-white" fill="white" />
            </div>
            <p className="text-sm font-bold text-white">FastFood SuperAdmin</p>
          </div>

          <div className="mb-8">
            <h1 className="text-2xl font-bold text-white mb-1">Sign in</h1>
            <p className="text-sm text-gray-500">Enter your SuperAdmin credentials to continue</p>
          </div>

          <form onSubmit={handleSubmit} className="space-y-4">
            {error && (
              <div className="flex items-center gap-2 p-3 rounded-lg bg-red-500/10 border border-red-500/20 text-sm text-red-400">
                <AlertCircle size={16} className="flex-shrink-0" />
                {error}
              </div>
            )}

            <div>
              <label className="block text-sm font-medium text-gray-400 mb-1">
                Email address
              </label>
              <input
                type="email"
                required
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                placeholder="admin@platform.com"
                className="w-full px-3 py-2.5 rounded-lg border border-gray-700 text-sm text-gray-200 placeholder-gray-600 focus:outline-none focus:ring-2 focus:ring-orange-500 focus:border-transparent transition"
                style={{ background: '#0d1117' }}
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-400 mb-1">
                Password
              </label>
              <input
                type="password"
                required
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                placeholder="••••••••"
                className="w-full px-3 py-2.5 rounded-lg border border-gray-700 text-sm text-gray-200 placeholder-gray-600 focus:outline-none focus:ring-2 focus:ring-orange-500 focus:border-transparent transition"
                style={{ background: '#0d1117' }}
              />
            </div>

            <button
              type="submit"
              disabled={loading}
              className="w-full py-2.5 px-4 rounded-lg bg-orange-500 hover:bg-orange-600 text-white font-semibold text-sm transition-colors disabled:opacity-60 disabled:cursor-not-allowed mt-2"
            >
              {loading ? 'Signing in…' : 'Sign In'}
            </button>
          </form>

          <p className="mt-8 text-xs text-center text-gray-700">
            Restricted to SuperAdmin accounts only
          </p>
        </div>
      </div>
    </div>
  )
}

// Frontend/src/app/pages/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { AuthService } from 'src/app/services/auth.service';
import { CartService } from 'src/app/services/cart.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent implements OnInit {
  loginForm: FormGroup;
  errorMessage = '';
  isLoading = false;
  showPassword = false;
  returnUrl: string | null = null;

  constructor(
    private fb: FormBuilder,
    private authService: AuthService,
    private cartService: CartService,
    private router: Router,
    private route: ActivatedRoute
  ) {
    this.loginForm = this.fb.group({
      email: ['', [Validators.required, Validators.email]],
      password: ['', [Validators.required, Validators.minLength(6)]]
    });
  }

  ngOnInit(): void {
    this.returnUrl = this.route.snapshot.queryParamMap.get('returnUrl');
  }

  onLogin(): void {
    this.loginForm.markAllAsTouched();
    if (this.loginForm.invalid) return;

    this.isLoading = true;
    this.errorMessage = '';

    this.authService.login(this.loginForm.value).subscribe({
      next: () => {
        const role = this.authService.getUserRole();
        const isCustomer = !role || role === 'ROLE_USER';

        const navigate = () => {
          if (this.returnUrl) {
            this.router.navigateByUrl(this.returnUrl, { replaceUrl: true });
          } else if (role === 'ROLE_SUPERADMIN') {
            this.router.navigate(['/superadmin'], { replaceUrl: true });
          } else if (role === 'ROLE_ADMIN') {
            this.router.navigate(['/admin/dashboard'], { replaceUrl: true });
          } else if (role === 'ROLE_DRIVER') {
            this.router.navigate(['/driver/dashboard'], { replaceUrl: true });
          } else {
            this.router.navigate(['/stores'], { replaceUrl: true });
          }
        };

        if (isCustomer) {
          this.cartService.mergeGuestCart().subscribe({ next: navigate, error: navigate });
        } else {
          navigate();
        }
      },
      error: () => {
        this.errorMessage = 'Invalid email or password';
        this.isLoading = false;
      }
    });
  }
}

<div class="min-h-screen bg-surface flex items-center justify-center p-4">
  <div class="w-full max-w-md animate-fade-in">

    <!-- Logo / Brand -->
    <div class="text-center mb-8">
      <div class="w-16 h-16 bg-primary rounded-2xl flex items-center justify-center mx-auto mb-4 shadow-md">
        <i class="bi bi-fire text-white text-2xl"></i>
      </div>
      <h1 class="font-heading text-2xl font-bold text-textDark">Welcome Back</h1>
      <p class="text-textLight text-sm mt-1">Sign in to your account</p>
      <div class="flex items-center justify-center gap-2 mt-3 flex-wrap">
        <span class="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-primary-50 text-primary text-xs font-medium">
          <i class="bi bi-bag-heart-fill text-[10px]"></i> Customers
        </span>
        <span class="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-primary-50 text-primary text-xs font-medium">
          <i class="bi bi-shop-window text-[10px]"></i> Restaurant Owners
        </span>
        <span class="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-primary-50 text-primary text-xs font-medium">
          <i class="bi bi-bicycle text-[10px]"></i> Drivers
        </span>
      </div>
    </div>

    <!-- Card -->
    <div class="bg-white rounded-2xl shadow-card p-8">
      <form [formGroup]="loginForm" (ngSubmit)="onLogin()" class="space-y-5" data-testid="login-form">

        <!-- Email -->
        <div>
          <label class="block text-sm font-medium text-textDark mb-1.5">Email</label>
          <div class="relative">
            <div class="absolute inset-y-0 left-0 pl-3.5 flex items-center pointer-events-none">
              <i class="bi bi-envelope text-textMuted"></i>
            </div>
            <input type="email" formControlName="email" data-testid="login-email"
                   class="w-full pl-10 pr-4 py-3 rounded-xl border bg-surface text-textDark
                          placeholder-textMuted text-sm
                          focus:outline-none focus:ring-2 focus:border-transparent transition-shadow"
                   [class.border-red-400]="loginForm.get('email')?.invalid && loginForm.get('email')?.touched"
                   [class.border-borderColor]="!(loginForm.get('email')?.invalid && loginForm.get('email')?.touched)"
                   [class.focus:ring-red-400]="loginForm.get('email')?.invalid && loginForm.get('email')?.touched"
                   [class.focus:ring-primary-400]="!(loginForm.get('email')?.invalid && loginForm.get('email')?.touched)"
                   placeholder="your@email.com" />
          </div>
          <p *ngIf="loginForm.get('email')?.touched && loginForm.get('email')?.hasError('required')"
             class="text-danger text-xs mt-1">Email is required</p>
          <p *ngIf="loginForm.get('email')?.touched && loginForm.get('email')?.hasError('email')"
             class="text-danger text-xs mt-1">Please enter a valid email address</p>
        </div>

        <!-- Password -->
        <div>
          <label class="block text-sm font-medium text-textDark mb-1.5">Password</label>
          <div class="relative">
            <div class="absolute inset-y-0 left-0 pl-3.5 flex items-center pointer-events-none">
              <i class="bi bi-lock text-textMuted"></i>
            </div>
            <input [type]="showPassword ? 'text' : 'password'" formControlName="password"
                   data-testid="login-password"
                   class="w-full pl-10 pr-12 py-3 rounded-xl border bg-surface text-textDark
                          placeholder-textMuted text-sm
                          focus:outline-none focus:ring-2 focus:border-transparent
                          transition-shadow"
                   [class.border-red-400]="loginForm.get('password')?.invalid && loginForm.get('password')?.touched"
                   [class.border-borderColor]="!(loginForm.get('password')?.invalid && loginForm.get('password')?.touched)"
                   [class.focus:ring-red-400]="loginForm.get('password')?.invalid && loginForm.get('password')?.touched"
                   [class.focus:ring-primary-400]="!(loginForm.get('password')?.invalid && loginForm.get('password')?.touched)"
                   placeholder="Enter your password" />
            <button type="button" (click)="showPassword = !showPassword"
                    data-testid="login-password-toggle"
                    class="absolute inset-y-0 right-0 pr-3.5 flex items-center text-textMuted hover:text-textDark transition-colors">
              <i [class]="showPassword ? 'bi bi-eye-slash' : 'bi bi-eye'"></i>
            </button>
          </div>
          <p *ngIf="loginForm.get('password')?.touched && loginForm.get('password')?.hasError('required')"
             class="text-danger text-xs mt-1">Password is required</p>
          <p *ngIf="loginForm.get('password')?.touched && loginForm.get('password')?.hasError('minlength')"
             class="text-danger text-xs mt-1">Password must be at least 6 characters</p>
        </div>

        <!-- Forgot password -->
        <div class="text-right -mt-2">
          <a routerLink="/forgot-password" class="text-xs text-primary hover:underline font-medium">Forgot password?</a>
        </div>

        <!-- Error -->
        <div *ngIf="errorMessage"
             data-testid="login-error"
             class="flex items-center gap-2 text-danger text-sm bg-red-50 px-4 py-2.5 rounded-xl">
          <i class="bi bi-exclamation-circle"></i>
          <span>{{ errorMessage }}</span>
        </div>

        <!-- Submit -->
        <app-button
          variant="primary"
          size="lg"
          type="submit"
          data-testid="login-submit"
          [fullWidth]="true"
          [loading]="isLoading"
          [disabled]="loginForm.invalid">
          Sign In
        </app-button>
      </form>
    </div>

    <!-- Register link -->
    <p class="text-center text-sm text-textLight mt-6">
      Don't have an account?
      <a [routerLink]="['/register']" [queryParams]="returnUrl ? { returnUrl: returnUrl } : {}"
         class="text-primary font-semibold hover:underline">Create one</a>
    </p>
  </div>
</div>
