// Frontend/src/app/shared/components/badge/badge.component.ts
import { Component, Input, ChangeDetectionStrategy } from '@angular/core';

export type BadgeVariant = 'primary' | 'success' | 'warning' | 'danger' | 'neutral';
export type BadgeSize = 'sm' | 'md';

@Component({
  selector: 'app-badge',
  template: `
    <span [class]="badgeClasses">
      <ng-content></ng-content>
    </span>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class BadgeComponent {
  @Input() variant: BadgeVariant = 'primary';
  @Input() size: BadgeSize = 'sm';

  get badgeClasses(): string {
    const base = 'inline-flex items-center font-semibold rounded-full';

    const variants: Record<BadgeVariant, string> = {
      primary: 'bg-primary-100 text-primary-700',
      success: 'bg-green-100 text-green-700',
      warning: 'bg-yellow-100 text-yellow-700',
      danger: 'bg-red-100 text-red-700',
      neutral: 'bg-gray-100 text-gray-700',
    };

    const sizes: Record<BadgeSize, string> = {
      sm: 'px-2 py-0.5 text-xs',
      md: 'px-3 py-1 text-sm',
    };

    return `${base} ${variants[this.variant]} ${sizes[this.size]}`;
  }
}

// SuperAdmin/frontend/src/components/common/Badge.tsx
type Variant = 'success' | 'warning' | 'danger' | 'neutral' | 'info'

interface BadgeProps {
  label: string
  variant: Variant
}

const variantMap: Record<Variant, string> = {
  success: 'bg-green-500/10 text-green-400 border-green-500/20',
  warning: 'bg-yellow-500/10 text-yellow-400 border-yellow-500/20',
  danger:  'bg-red-500/10 text-red-400 border-red-500/20',
  neutral: 'bg-gray-700/50 text-gray-400 border-gray-700',
  info:    'bg-blue-500/10 text-blue-400 border-blue-500/20'
}

export default function Badge({ label, variant }: BadgeProps) {
  return (
    <span
      className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium border ${variantMap[variant]}`}
    >
      {label}
    </span>
  )
}
